<?php
if (function_exists('acf_add_local_field_group')) :

    acf_add_local_field_group(array(
        'key' => 'home-fields',
        'title' => 'Home Fields',
        'fields' => array(
            array(
                'key' => 'field_6586ec932087b',
                'label' => 'Hero Title',
                'name' => 'hero_title',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_6586ecfa0bb25',
                'label' => 'What We Do',
                'name' => 'what_we_do',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'show_in_graphql' => 1,
                'graphql_description' => '',
                'graphql_field_name' => 'whatWeDo',
                'graphql_non_null' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_65c263b3a6a4b',
                        'label' => 'Title',
                        'name' => 'title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'show_in_graphql' => 1,
                        'graphql_description' => '',
                        'graphql_field_name' => 'title',
                        'graphql_non_null' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_65c263b7a6a4c',
                        'label' => 'Pills',
                        'name' => 'pills',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'show_in_graphql' => 1,
                        'graphql_description' => '',
                        'graphql_field_name' => 'pills',
                        'graphql_non_null' => 0,
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_65c263c7a6a4d',
                                'label' => 'Pill Text',
                                'name' => 'pill_text',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'show_in_graphql' => 1,
                                'graphql_description' => '',
                                'graphql_field_name' => 'pillText',
                                'graphql_non_null' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_6586ed84947a4',
                'label' => 'Showcase Title',
                'name' => 'showcase_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_6586edb48e72b',
                'label' => 'Skills Title',
                'name' => 'skills_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_6586ee3b00320',
                'label' => 'Approach',
                'name' => 'approach',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_65c26517a9103',
                        'label' => 'Title',
                        'name' => 'title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'show_in_graphql' => 1,
                        'graphql_description' => '',
                        'graphql_field_name' => 'title',
                        'graphql_non_null' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_65c26521a9104',
                        'label' => 'Paragraph',
                        'name' => 'paragraph',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'show_in_graphql' => 1,
                        'graphql_description' => '',
                        'graphql_field_name' => 'paragraph',
                        'graphql_non_null' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '9',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'permalink',
            1 => 'the_content',
            2 => 'excerpt',
            3 => 'discussion',
            4 => 'comments',
            5 => 'revisions',
            6 => 'slug',
            7 => 'author',
            8 => 'format',
            9 => 'page_attributes',
            10 => 'categories',
            11 => 'tags',
            12 => 'send-trackbacks',
        ),
        'active' => true,
        'description' => '',
        'show_in_graphql' => 1,
        'graphql_field_name' => 'homeFields',
        'map_graphql_types_from_location_rules' => 0,
        'graphql_types' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_65c252d362028',
        'title' => 'Project Fields',
        'fields' => array(
            array(
                'key' => 'field_65c252de50e50',
                'label' => 'Stat 1',
                'name' => 'stat_1',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'row',
                'sub_fields' => array(
                    array(
                        'key' => 'field_65c2531150e51',
                        'label' => 'Field',
                        'name' => 'field',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_65c2531b50e52',
                        'label' => 'Value',
                        'name' => 'value',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_65c2532a50e53',
                'label' => 'Stat 2',
                'name' => 'stat_2',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'row',
                'sub_fields' => array(
                    array(
                        'key' => 'field_65c2532a50e54',
                        'label' => 'Field',
                        'name' => 'field',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_65c2532a50e55',
                        'label' => 'Value',
                        'name' => 'value',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_65c2533a12b88',
                'label' => 'Stat 3',
                'name' => 'stat_3',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'row',
                'sub_fields' => array(
                    array(
                        'key' => 'field_65c2533a12b89',
                        'label' => 'Field',
                        'name' => 'field',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_65c2533a12b8a',
                        'label' => 'Value',
                        'name' => 'value',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_65c253e0692e6',
                'label' => 'Content',
                'name' => 'content',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layouts' => array(
                    'layout_65c253f2130cc' => array(
                        'key' => 'layout_65c253f2130cc',
                        'name' => 'large_text_area',
                        'label' => 'Large Text Area',
                        'display' => 'row',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_65c25418692e7',
                                'label' => 'Large Text Area',
                                'name' => 'large_text_area',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_65c255dac79de' => array(
                        'key' => 'layout_65c255dac79de',
                        'name' => 'gallery_1',
                        'label' => 'Gallery 1',
                        'display' => 'row',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_65c255dac79e0',
                                'label' => 'Gallery 1',
                                'name' => 'gallery_1',
                                'type' => 'gallery',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => '',
                                'preview_size' => 'medium',
                                'insert' => 'append',
                                'library' => '',
                                'min' => '',
                                'max' => '',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_65c25600c79eb' => array(
                        'key' => 'layout_65c25600c79eb',
                        'name' => 'gallery_2',
                        'label' => 'Gallery 2',
                        'display' => 'row',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_65c25600c79ed',
                                'label' => 'Gallery 2',
                                'name' => 'gallery_2',
                                'type' => 'gallery',
                                'instructions' => 'Max 2 Images',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => '',
                                'preview_size' => 'medium',
                                'insert' => 'append',
                                'library' => '',
                                'min' => '',
                                'max' => '',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_65c25610c79f7' => array(
                        'key' => 'layout_65c25610c79f7',
                        'name' => 'the_challenge',
                        'label' => 'The Challenge',
                        'display' => 'row',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_65c25610c79f9',
                                'label' => 'Dynamic Text and Image',
                                'name' => 'dynamic_text_and_image',
                                'type' => 'flexible_content',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layouts' => array(
                                    'layout_65c2546b8c2ed' => array(
                                        'key' => 'layout_65c2546b8c2ed',
                                        'name' => 'text',
                                        'label' => 'Text',
                                        'display' => 'row',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_65c25610c79fa',
                                                'label' => 'Text',
                                                'name' => 'text',
                                                'type' => 'text',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'placeholder' => '',
                                                'prepend' => '',
                                                'append' => '',
                                                'maxlength' => '',
                                            ),
                                        ),
                                        'min' => '',
                                        'max' => '',
                                    ),
                                    'layout_65c257a30f937' => array(
                                        'key' => 'layout_65c257a30f937',
                                        'name' => 'text_and_image',
                                        'label' => 'Text and Image',
                                        'display' => 'row',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_65c257a30f93a',
                                                'label' => 'Text',
                                                'name' => 'text',
                                                'type' => 'text',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'placeholder' => '',
                                                'prepend' => '',
                                                'append' => '',
                                                'maxlength' => '',
                                            ),
                                            array(
                                                'key' => 'field_65c257a30f93b',
                                                'label' => 'Image',
                                                'name' => 'image',
                                                'type' => 'image',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'return_format' => 'array',
                                                'preview_size' => 'medium',
                                                'library' => 'all',
                                                'min_width' => '',
                                                'min_height' => '',
                                                'min_size' => '',
                                                'max_width' => '',
                                                'max_height' => '',
                                                'max_size' => '',
                                                'mime_types' => '',
                                            ),
                                        ),
                                        'min' => '',
                                        'max' => '',
                                    ),
                                ),
                                'button_label' => 'Add Row',
                                'min' => '',
                                'max' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_65c2562cc7a02' => array(
                        'key' => 'layout_65c2562cc7a02',
                        'name' => 'paragraph_field',
                        'label' => 'Paragraph Field',
                        'display' => 'row',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_65c2562dc7a09',
                                'label' => 'Paragraph Item',
                                'name' => 'paragraph_item',
                                'type' => 'flexible_content',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layouts' => array(
                                    'layout_65c259423101d' => array(
                                        'key' => 'layout_65c259423101d',
                                        'name' => 'title',
                                        'label' => 'Title',
                                        'display' => 'block',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_65c2593be15b1',
                                                'label' => 'Title',
                                                'name' => 'title',
                                                'type' => 'text',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'placeholder' => '',
                                                'prepend' => '',
                                                'append' => '',
                                                'maxlength' => '',
                                            ),
                                        ),
                                        'min' => '',
                                        'max' => '',
                                    ),
                                    'layout_65c25950e15b2' => array(
                                        'key' => 'layout_65c25950e15b2',
                                        'name' => 'paragraph',
                                        'label' => 'Paragraph',
                                        'display' => 'block',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_65c257e0b12ab',
                                                'label' => 'Paragraph',
                                                'name' => 'paragraph',
                                                'type' => 'textarea',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'placeholder' => '',
                                                'maxlength' => '',
                                                'rows' => '',
                                                'new_lines' => '',
                                            ),
                                        ),
                                        'min' => '',
                                        'max' => '',
                                    ),
                                    'layout_65c2595de15b4' => array(
                                        'key' => 'layout_65c2595de15b4',
                                        'name' => 'large_paragraph',
                                        'label' => 'Large Paragraph',
                                        'display' => 'block',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_65c257f2b12b0',
                                                'label' => 'Large Paragraph',
                                                'name' => 'large_paragraph',
                                                'type' => 'textarea',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'placeholder' => '',
                                                'maxlength' => '',
                                                'rows' => '',
                                                'new_lines' => '',
                                            ),
                                        ),
                                        'min' => '',
                                        'max' => '',
                                    ),
                                ),
                                'button_label' => 'Add Row',
                                'min' => '',
                                'max' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                ),
                'button_label' => 'Add Row',
                'min' => '',
                'max' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'project',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'permalink',
            1 => 'the_content',
            2 => 'excerpt',
            3 => 'discussion',
            4 => 'comments',
            5 => 'revisions',
            6 => 'slug',
            7 => 'author',
            8 => 'format',
            9 => 'page_attributes',
            10 => 'categories',
            11 => 'send-trackbacks',
        ),
        'active' => true,
        'description' => '',
    ));

endif;
